function kk=Modelo_1_h(x)

global v 

Mo1=figure(3);
 set(Mo1,'name','Model 1','numbertitle','off','Position', [600,200,300,300],'Units','pixels','menubar','none','units','normalized')
 

 Hidro_Tex=uicontrol('Parent',Mo1,...
           'Style','text',...
           'Position',[5 250 100 25],...
           'String','Variables Modelo');
 
 d50_Text=uicontrol('Parent',Mo1,...
           'Style','text',...
           'Position',[5 90 50 25],...
           'String','d50');
 alfa_Text=uicontrol('Parent',Mo1,...
           'Style','text',...
           'Position',[5 140 50 25],...
           'String','alfa');
 Cortocircuito_Text=uicontrol('Parent',Mo1,...
           'Style','text',...
           'Position',[5 190 150 25],...
           'String','Cortocircuito');
 
 d50_Edit = uicontrol('Parent',Mo1,...
           'Style','edit',...
           'Position',[160 90 50 25],...
           'String','100');
 alfa_Edit = uicontrol('Parent',Mo1,...
           'Style','edit',...
           'Position',[160 140 50 25],...
           'String','0.5');
       
 Cortocircuito_Edit= uicontrol('Parent',Mo1,...
           'Style','edit',...
           'Position',[160 190 50 25],...
           'String','0');
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%      
             
 cerrar_mo1 = uicontrol('Parent',Mo1,...
           'Style','push',...
           'Position',[150 10 100 25],...
           'String','Cerrar',...
           'Callback',@cerrar);
aceptar_mo1=uicontrol;
d50_Edit.UserData=x;
aceptar_mo1.UserData=[d50_Edit alfa_Edit Cortocircuito_Edit];

 set(aceptar_mo1,'Parent',Mo1,...
           'Style','push',...
           'Position',[5 10 100 25],...
           'String','Aceptar',...
           'Callback',@create_matrixh1);
     
waitfor(Mo1)
end