function Hidrociclon_modelos_edit(source,callbackdata)

global popup_mo 


 x = get_index(source);
 k=figure;
 set(k,'name','Model Selection','numbertitle','off','Position', [500,500,200,200],'Units','pixels','menubar','none','units','normalized')
 
 popup_mo=uicontrol('Parent',k,...
           'Style','popup',...
           'Position',[25 150 100 25],...
           'String',{'Modelo 1'},'Value',1);
 
 Aceptar = uicontrol('Parent',k,...
           'Style','push',...
           'Position',[25 90 100 25],...
           'String','Aceptar',...
           'Callback',@popup_callbackmo);
 cerrar2 = uicontrol('Parent',k,...
           'Style','push',...
           'Position',[25 40 100 25],...
           'String','Close',...
           'Callback',@cerrar);
  x=source.UserData;
  
  function popup_callbackmo(hObject,~)
          elec=get(popup_mo,'Value');  
          close(hObject.Parent);
    if elec ==1
      edit_modelo1_h(x)
    end
    
  end
end